version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:  
      - type: bind
        source: ./server/config.ini
        target: /config/config.ini
        read_only: true

  server-test:
    container_name: server-test
    image: server-test:latest
    entrypoint: /server-test.sh
    networks:
      - testing_net
    depends_on:
      - server
    profiles:
      - tests 

  client1:
    container_name: client1
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:  
      - type: bind
        source: ./client/config.yaml
        target: /config/config.yaml
        read_only: true
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:  
      - type: bind
        source: ./client/config.yaml
        target: /config/config.yaml
        read_only: true
    depends_on:
      - server

volumes:
  server-config:
    external: false
  client-config:
    external: false

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
